# 1. Numpy and Linear Algebra (선형대수)

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [1]:
import numpy as np
x = 6
x

6

In [2]:
x = np.array([1])
x.shape

(1,)

In [3]:
x = np.array([1,2,3])
x.shape #요소가 3개인 1차원 array 벡터

(3,)

In [4]:
x

array([1, 2, 3])

In [5]:
np.argmax(x) #인덱스가 가장 큰 값, 가장 큰 인덱스 = 2

2

In [6]:
x.argmax()

2

In [7]:
y = np.array([[1,2,3],[2,3,4],[5,6,7],[8,9,10]])
y

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
y.shape

(4, 3)

In [9]:
z = np.array([[[1,2,3],[2,3,4]],[[5,6,7],[8,9,10]]])
print(z) #3차원 array = 텐서

[[[ 1  2  3]
  [ 2  3  4]]

 [[ 5  6  7]
  [ 8  9 10]]]


In [10]:
z.shape

(2, 2, 3)

## Indexing / Slicing

<img src="axes.png" width="600">

<img src="numpy.png" width="400">



<img src="tensor.jpg" width="600">

## Slicing (두번째,세번째 슬라이싱 방법은 머신러닝 할 때 항상 사용되는 슬라이싱 요령)
두번째 슬라이싱 : ex) 데이터가 3만 건이 있는데 앞에 2만 건은 훈련용으로 쓰고 뒤에 1만건은 검증용으로 쓸 때 이렇게 자름, 일반적으로 머신러닝에선 행렬 형태의 데이터로 많이 들어감. 행렬 형태로 구성하는 방법도 알아야 pytorch나 tenserflow 같은 라이브러리 함수를 부를때 입력 사양을 맞춰줄 수 있음. 

세번째 슬라이싱 : ex) 데이터의 칼럼이 3개가 있는데 첫번째,두번째 칼럼은 우리가 훈련을 위한 입력용으로 사용하고 세 번째 칼럼은 지도학습의 정답 데이터(feature), 데이터의 특성 칼럼, 정답 또는 타켓(Label) 칼럼을 구분할 때 자르는 슬라이싱 방법

<img src="numpy1.png" width="300">

In [11]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(arr[:2,1:])

[[2 3]
 [5 6]]


In [13]:
print(arr[2:]) #벡터형태
print(arr[2]) #벡터형태
print(arr[2::]) #행렬형태
print(arr[2::].shape)

[[7 8 9]]
[7 8 9]
[[7 8 9]]
(1, 3)


In [14]:
print(arr[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [15]:
print(arr[1,:2]) #vector 형태, 요소가 2인 형태
print(arr[1:2, :2]) #행렬 형태, 대괄호가 하나 더 생김
print(arr[1:2, :2].shape)

[4 5]
[[4 5]]
(1, 2)


### 벡터의 내적(inner product) 
- 내적이 되려면 두 벡터의 dimension 이 같아야 한다. 내적은 각 element 의 곱을 모두 더한 것이다.
- inner product 은 dot product (점곱) 이라고도 불린다.
- 내적을 딥러닝,전통적인 머신러닝도 마찬가지고 딥러닝은 뉴럴 네트워크 내부에서 전부 내적으로 연산이 됨
- 벡터 간의 연산이고 벡터가 여러 개 모인 것이 행렬, 행렬의 연산이 전부 행벡터하고 열벡터 간의 내적이 합쳐진게 행렬 곱셈인데 이 원리를 아는 것이 필요
- - 어차피 텐서플로나 파이토치 같은 프레임워크가 대신 다 해주기 때문에 직접 코딩할 일은 없지만 원리는 이해해야함. 내적에 의해서 다 연산이 이뤄짐

In [16]:
a = np.array([2,5,1])
print(a)

[2 5 1]


In [17]:
b = np.array([4,3,5])
print(b)

[4 3 5]


$\mathbf{a}\mathbf{b}^T = \begin{bmatrix} 2 & 5 & 1\end{bmatrix}\begin{bmatrix}4\\3\\5\end{bmatrix} = \begin{bmatrix}2*4 + 5*3 + 1*5\end{bmatrix} = 28$

In [18]:
#a,b의 내적 --> scaler
np.dot(a,b)

28

## matrix 곱셈 (행렬 곱셈, dot product)

### 두 행렬 A 와 B 는 A 의 열(column) 갯수가 B 의 행(row) 갯수와 같을 때 곱할 수 있다. 결과 행렬 C 의 shape 은 A 의 row x B 의 column 이 된다.
뉴럴 네트워크 내부는 전부 이런 행렬의 곱셈 연산. 하나는 입력 데이터고 또 하나는 뉴럴네트워크가 스스로 학습한 가중치 행렬 그 두 가지를 행렬 곱을 해서 뉴럴 네트워크 내부의 계산이 이뤄지게 되는데 전부 하나하나로 보면 위에서 말한 내적으로 되어 있음


<img src="matmul2.png" width="250">
<img src="matmul.png" width="350">

$$\mathbf{A} = \begin{bmatrix}2&5&1\\4&5&3\end{bmatrix} \text{ and } \mathbf{B}=\begin{bmatrix}4&3&5&7\\9&5&3&4\\5&3&6&7\end{bmatrix}$$
$$\mathbf{AB} = \begin{bmatrix}2*4+5*9+1*5&2*3+5*5+1*3&2*5+5*3+1*6&2*7+5*4+1*7\\4*4+5*9+3*5&4*3+5*5+3*3&4*5+5*3+3*6&4*7+5*4+3*7\end{bmatrix}$$

In [19]:
a = np.array([[2,1],[1,4]])
b = np.array([[1,2,0],[0,1,2]])
print(np.matmul(a,b)) # matmul만 해주면 행렬 곱셈 연산이 수행

[[2 5 2]
 [1 6 8]]


### 전치행렬 (Transposed Matrix)
transpose하고 reshape이 많이 쓰이는데 전치행렬 같은 경우에는 행,칼럼하고 바뀜. 
- 보통 입력 사양들을 맞춰줄때 씀
- 텐서플로,파이토치가 원하는 데이터 모양으로 바꿔줘야함, 그래서 전치를 쓰는 경우가 많음


In [20]:
list(range(9))

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [21]:
A = np.arange(9) # 요소가 9개인 벡터 --> 근데 이걸 3*3인 행렬로 바꾸고 싶
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
B = A.reshape(3,3)
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
B.T #B의 전치행렬
np.transpose(b)
B.transpose() #다 동일한 코드식

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])